server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.0.240:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: czfx
    password: czfx1
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 20000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat.log-slow-sql: true
        stat.slow-sql-millis: 10000

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.cmkj.mall: debug
#  file: demo_log.log #配置日志生成路径
  path: /data/logs #配置日志文件名称

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql





